# Generated by Django 4.1.2 on 2022-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaplan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="code",
            field=models.CharField(default="A", max_length=5),
        ),
    ]
