# Generated by Django 4.1.2 on 2022-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaplan", "0002_device_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetdevice",
            name="code",
            field=models.CharField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name="targetdevice",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
